### ISSUE TITLE
Antisocial NPC birthdays cause errors

### ISSUE THREAD

**Issue by elizabethcd** [Annosz/UIInfoSuite2#167]
When there are modded NPCs that are antisocial but have a birthday defined, this causes this mod to throw a lot of errors. This is true for more than one modded NPC (based on user reports).

Here's a sample log from a user: https://smapi.io/log/080d70a82e6a4484b7c82b2e26269c10?renew=True&Levels=error%7Ecritical

In case the log expires, the error is:
This mod failed in the Display.RenderingHud event. Technical details: 
System.Collections.Generic.KeyNotFoundException: The given key 'Mia' was not present in the dictionary.
key: 'Mia'
   at System.Collections.Generic.Dictionary`2[[System.String, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[StardewValley.GameData.SpecialOrderData, StardewValley.GameData, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].get_Item_Patch1(Dictionary`2 this, String key)
   at Netcode.NetDictionary`5.get_Item(TKey key) in stardewvalley\Farmer\Netcode\NetDictionary.cs:line 71
   at UIInfoSuite.UIElements.ShowBirthdayIcon.DrawBithdayIcon()
   at UIInfoSuite.UIElements.ShowBirthdayIcon.OnRenderingHud(Object sender, EventArgs e)
   at StardewModdingAPI.Framework.Events.ManagedEvent`1.Raise(TEventArgs args, Func`2 match) in SMAPI\Framework\Events\ManagedEvent.cs:line 126

**Comment by Annosz** [comment]
Hi! Sorry this issue took so much time to fix, I just did not realized that it is actually a breaking error which makes you unable to play the game...
I uploaded version 2.2.4 of the mod, which is the fix for this issue - you will be able to use the birthday icon again.
