### ISSUE TITLE
this issues apper after i updated some other mods

### ISSUE THREAD

**Issue by jmsczbdhr** [Annosz/UIInfoSuite2#176]
[UI Info Suite 2] This mod failed in the Display.RenderingHud event. Technical details:
System.Collections.Generic.KeyNotFoundException: The given key 'Marlon' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Netcode.NetDictionary`5.get_Item(TKey key) in stardewvalley\Farmer\Netcode\NetDictionary.cs:line 71
   at UIInfoSuite.UIElements.ShowBirthdayIcon.DrawBithdayIcon()
   at UIInfoSuite.UIElements.ShowBirthdayIcon.OnRenderingHud(Object sender, EventArgs e)
   at StardewModdingAPI.Framework.Events.ManagedEvent`1.Raise(TEventArgs args) in SMAPI\Framework\Events\ManagedEvent.cs:line 101

**Comment by KAVH5** [comment]
Hey, this is an open issue. Here's the link to the original person it happened to, with Marlon as well.
https://github.com/Annosz/UIInfoSuite2/issues/171 ... 

It happened to me with 'Bill' and someone else with 'Mia.' It's happening with added characters/NPCs, I believe.
The solution is to disable the show birthday option in the UI Info Suite config-menu. You can go read the forum yourself to see if you understand the commenters more. I unfortunately am not understanding or have the mod installed incorrectly which I have downloaded and re-added so not so sure that's the issue. If you are able to fix could you let me know. 

Happy gaming friend!

**Comment by Annosz** [comment]
Hi! Sorry this issue took so much time to fix, I just did not realized that it is actually a breaking error which makes you unable to play the game...
I uploaded version 2.2.4 of the mod, which is the fix for this issue - you will be able to use the birthday icon again.
