### ISSUE TITLE
Error message in smapi

### ISSUE THREAD

**Issue by Drextragon** [Annosz/UIInfoSuite2#202]
Title
here is the error message : 
[UI Info Suite 2] This mod failed in the GameLoop.GameLaunched event. Technical details:
ArgumentException: The IGenericModConfigMenuApi interface defines method Register which doesn't exist in the API.
   at Nanoray.Pintail.ProxyManagerConfiguration`1.<>c.<.cctor>b__15_4(TypeBuilder proxyBuilder, ProxyInfo`1 proxyInfo, FieldBuilder _, FieldBuilder _, FieldBuilder _, MethodInfo proxyMethod)
   at Nanoray.Pintail.InterfaceOrDelegateProxyFactory`1.Prepare(ProxyManager`1 manager, String typeName)
   at Nanoray.Pintail.ProxyManager`1.ObtainProxyFactory(ProxyInfo`1 proxyInfo)
   at Nanoray.Pintail.IProxyManagerExtensions.ObtainProxy[Context,TProxy](IProxyManager`1 self, Object instance, Context targetContext, Context proxyContext)
   at StardewModdingAPI.Framework.ModHelpers.ModRegistryHelper.GetApi[TInterface](String uniqueID) in SMAPI\Framework\ModHelpers\ModRegistryHelper.cs:line 98
   at UIInfoSuite.ModEntry.OnGameLaunched(Object sender, GameLaunchedEventArgs e)
   at StardewModdingAPI.Framework.Events.ManagedEvent`1.Raise(TEventArgs args) in SMAPI\Framework\Events\ManagedEvent.cs:line 101

**Comment by tqdv** [comment]
Hi, I think your version of Generic Mod Config Menu is too old. What version do you have?
UI Info Suite requires at least version 1.5.0.

**Comment by Annosz** [comment]
A little update will be available in the 2.2.6 version that will warn about this error and will prevent the mod from crashing, thanks to @tqdv.
