### ISSUE TITLE
Unexplained Crash

### ISSUE THREAD

**Issue by goldberry2000** [Annosz/UIInfoSuite2#301]
I did try to work out what exactly was happening, but honestly the code is a little beyond my skill level-- I've had a few crashes similar to the attached: [](https://smapi.io/log/999828da8b214acbbb6d24822af8c115). Please bear in mind this is a partial log, with the initial day of the play session and the final day of the session, as the log was too large for the log parser to process. I do have the full version if that would help at all.

The jist seems to be ExtraMapLayers and UIInfoSuite having a bit of a tug of war. The following two errors repeat:

<html>
<body>

UI Info Suite 2 | This mod failed in the Display.RenderedActiveMenu event. Technical details:  NullReferenceException: Object reference not set to an instance of an object.    at UIInfoSuite2.Options.ModOptionsPageHandler.DrawButton(GameMenu gameMenu) in /alt/vm_host/StardewValleyModding/UIInfoSuite2/UIInfoSuite2/Options/ModOptionsPageHandler.cs:line 245    at UIInfoSuite2.Options.ModOptionsPageHandler.OnRenderedMenu(Object sender, RenderedActiveMenuEventArgs e) in /alt/vm_host/StardewValleyModding/UIInfoSuite2/UIInfoSuite2/Options/ModOptionsPageHandler.cs:line 201    at StardewModdingAPI.Framework.Events.ManagedEvent`1.Raise(TEventArgs args) in SMAPI\Framework\Events\ManagedEvent.cs:line 101
-- | --

</body>
</html>

<html>
<body>

UI Info Suite 2 | This mod failed in the Display.RenderingActiveMenu event. Technical details:  NullReferenceException: Object reference not set to an instance of an object.    at UIInfoSuite2.Options.ModOptionsPageHandler.DrawButton(GameMenu gameMenu) in /alt/vm_host/StardewValleyModding/UIInfoSuite2/UIInfoSuite2/Options/ModOptionsPageHandler.cs:line 245    at StardewModdingAPI.Framework.Events.ManagedEvent`1.Raise(TEventArgs args) in SMAPI\Framework\Events\ManagedEvent.cs:line 101
-- | --

</body>
</html>

Then it swaps to:

<html>
<body>

An error occurred in the overridden draw loop: System.Collections.Generic.KeyNotFoundException: The given key 'Component: outdoors' was not present in the dictionary.    at System.Collections.Generic.Dictionary`2.get_Item(TKey key)    at StardewModdingAPI.Framework.Rendering.SDisplayDevice.DrawTile_PatchedBy<aedenthorn.ExtraMapLayers>(SDisplayDevice this, Tile tile, Location location, Single layerDepth)    at xTile.Layers.Layer.DrawNormal_PatchedBy<aedenthorn.ExtraMapLayers>(Layer this, IDisplayDevice displayDevice, Rectangle mapViewport, Location displayOffset, Int32 pixelZoom)    at xTile.Layers.Layer.Draw_PatchedBy<aedenthorn.ExtraMapLayers>(Layer this, IDisplayDevice displayDevice, Rectangle mapViewport, Location displayOffset, Boolean wrapAround, Int32 pixelZoom)    at StardewModdingAPI.Framework.SGame.DrawImpl_PatchedBy<tlitookilakin.AeroCore>(SGame this, GameTime gameTime, RenderTarget2D target_screen)    at StardewModdingAPI.Framework.SGame._draw(GameTime gameTime, RenderTarget2D target_screen)
--

</body>
</html>

Which iterates until the game crashes outright. In-game (split-screen), Player 1's screen goes black while Player 2's remains visible but unmovable with music continuing to play until SMAPI drops out.

I hope this is enough info, if not please give me a shout.

**Comment by Akkowicz** [comment]
Hi, I'm encountering a similar issue

Do you have any other mods installed? Full list would certainly help :)
I've had this crash occur as well, but it seems to be related to map layers.
