### ISSUE TITLE
[Bug]: Error with Luck Skill mod on levelup

### ISSUE THREAD

**Issue by argon932** [Annosz/UIInfoSuite2#466]
### Mod Version

v2.3.1

### Multiplayer

Single Player

### SMAPI Log

https://smapi.io/log/ab71c7d6c6bb4f07a8892a5bc106c1ae

### Issue
Error when leveling up with Luck Skill installed.

### Steps to Reproduce
Install Luck Skill mod. https://www.nexusmods.com/stardewvalley/mods/521
Level up.
Sleep.
I have a feeling this is is happening with all skill mods (binning, socalizing, cooking, etc)

[UI Info Suite 2] This mod failed in the Player.LevelChanged event. Technical details:
System.Collections.Generic.KeyNotFoundException: The given key 'Luck' was not present in the dictionary.
   at UIInfoSuite2.UIElements.ExperienceBar.OnLevelChanged(Object sender, LevelChangedEventArgs e) in C:\Users\Drew\RiderProjects\DH-UIInfoSuite2\UIInfoSuite2\UIElements\ExperienceBar.cs:line 185
   at StardewModdingAPI.Framework.Events.ManagedEvent`1.Raise(TEventArgs args) in SMAPI\Framework\Events\ManagedEvent.cs:line 101

**Comment by drewhoener** [comment]
Will be fixed when #339 is merged, thank you for the report
